# Generated by Django 5.2.17 on 2026-08-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatomoLauf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestartet', models.DateTimeField(auto_now_add=True)),
                ('beendet', models.DateTimeField(blank=True, null=True)),
                ('datum_von', models.DateField()),
                ('datum_bis', models.DateField()),
                ('berichte_ok', models.PositiveIntegerField(default=0)),
                ('berichte_fehler', models.PositiveIntegerField(default=0)),
                ('meldung', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Matomo-Abgleich',
                'verbose_name_plural': 'Matomo-Abgleiche',
                'ordering': ['-gestartet'],
            },
        ),
        migrations.CreateModel(
            name='MatomoSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(db_index=True, help_text='Erster Tag des Zeitraums')),
                ('periode', models.CharField(choices=[('day', 'Tag'), ('week', 'Woche'), ('month', 'Monat'), ('year', 'Jahr')], default='day', max_length=10)),
                ('unique_id', models.CharField(db_index=True, help_text='uniqueId aus API.getReportMetadata, z.B. Actions_getPageUrls', max_length=255)),
                ('modul', models.CharField(max_length=100)),
                ('aktion', models.CharField(max_length=100)),
                ('kategorie', models.CharField(blank=True, max_length=150)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('daten', models.JSONField(default=list)),
                ('zeilen', models.PositiveIntegerField(default=0)),
                ('abgerufen_am', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Matomo-Bericht',
                'verbose_name_plural': 'Matomo-Berichte',
                'ordering': ['-datum', 'kategorie', 'name'],
                'indexes': [models.Index(fields=['periode', 'datum'], name='matomo_mato_periode_6de57e_idx')],
                'constraints': [models.UniqueConstraint(fields=('datum', 'periode', 'unique_id'), name='matomo_snapshot_eindeutig')],
            },
        ),
    ]
