# Generated by Django 5.0.14 on 2026-04-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CollectivesConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nextcloud_url",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "kollektive_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("username", models.CharField(blank=True, default="", max_length=100)),
                (
                    "app_password",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("connected", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "collectives_config",
            },
        ),
        migrations.CreateModel(
            name="PageStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(db_index=True, max_length=512, unique=True)),
                ("status", models.CharField(blank=True, default="", max_length=50)),
                ("typ", models.CharField(blank=True, default="", max_length=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Page Statuses",
                "db_table": "collectives_pagestatus",
            },
        ),
    ]
