# Generated by Django 5.0.14 on 2026-04-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LinkedinPostPosted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_link",
                    models.CharField(
                        max_length=512, unique=True, verbose_name="Post-Link"
                    ),
                ),
                (
                    "post_id",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="Post-ID",
                    ),
                ),
                (
                    "post_title",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Titel"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Erstellt am"
                    ),
                ),
                (
                    "post_date",
                    models.DateField(verbose_name="Tatsaechlich gepostet am"),
                ),
                (
                    "post_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="post_images/",
                        verbose_name="Post-Bild",
                    ),
                ),
            ],
            options={
                "db_table": "linkedin_posts_posted",
                "ordering": ["-post_date"],
                "managed": False,
            },
        ),
    ]
